apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
          - name: RABBIT_HOST 
            value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
          - name: RABBIT_PORT
            value: "5672"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_DB
            value: "emotions_db"
          - name: MYSQL_USER
            value: "root"
          ports:
            - containerPort: 3306
              name: database
          volumeMounts:
            - name: database-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: database-persistent-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: LoadBalancer
  selector:
    app: database
  ports:
    - protocol: TCP
      name: http
      port: 3306
      targetPort: 3306
