---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: jeykime/backend:latest
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: RABBIT_HOST
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_CONSUMER_QUEUE
              value: "emotions_queue"
            - name: HOST
              value: "192.168.49.2"
            - name: PORT
              value: "32002"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
    tier: backend
  type: NodePort # type of the service.
  ports:
    - protocol: TCP
      port: 5000 # The port that the service is running on in the cluster
      targetPort: 5000 # The port exposed by the service
      nodePort: 32000
