apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotions
  labels:
    app: emotions
spec:
  selector:
    matchLabels:
      app: emotions
  replicas: 1
  template:
    metadata:
      labels:
        app: emotions
    spec:
      containers:
        - name: emotions
          image: jeykime/vision:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: RABBIT_HOST
              value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_PRODUCER_QUEUE
              value: "emotions-queue"

---
apiVersion: v1
kind: Service
metadata:
  name: emotions
spec:
  selector:
    app: emotions
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
